export const categories = [
  {
    id: "rc1",
    name: "Горячее",
    fullName: "Горячие блюда",
    img: "images/recipes/category-1.jpg",
  },
  {
    id: "rc2",
    name: "Супы",
    fullName: "Супы",
    img: "images/recipes/category-2.jpg",
  },
  {
    id: "rc3",
    name: "Салаты",
    fullName: "Салаты",
    img: "images/recipes/category-3.jpg",
  },
  {
    id: "rc4",
    name: "Десерты",
    fullName: "Десерты",
    img: "images/recipes/category-4.jpg",
  },
  {
    id: "rc5",
    name: "Закуски",
    fullName: "Закуски",
    img: "images/recipes/category-5.jpg",
  },
  {
    id: "rc6",
    name: "Выпечка",
    fullName: "Выпечка",
    img: "images/recipes/category-6.jpg",
  },
  {
    id: "rc7",
    name: "Заготовки",
    fullName: "Заготовки",
    img: "images/recipes/category-7.jpg",
  },
  {
    id: "rc8",
    name: "Напитки",
    fullName: "Напитки",
    img: "images/recipes/category-8.jpg",
  },
  {
    id: "rc9",
    name: "Соусы",
    fullName: "Соусы",
    img: "images/recipes/category-9.jpg",
  },
];

export const recipes = [
  {
    id: "r1",
    name: "Омлет классический с сыром и ветчиной",
    category: "rc1",
    img: "images/recipes/recipe-1.jpg",
    time: 30,
    difficulty: 2,
  },
  {
    id: "r2",
    name: "Яичница",
    category: "rc1",
    img: "images/recipes/recipe-2.jpg",
    time: 10,
    difficulty: 1,
  },
  {
    id: "r3",
    name: "Тыквенный суп",
    category: "rc2",
    img: "images/recipes/recipe-3.jpg",
    time: 60,
    difficulty: 2,
  },
  {
    id: "r4",
    name: "Овощной салат",
    category: "rc3",
    img: "images/recipes/recipe-4.jpg",
    time: 15,
    difficulty: 1,
  },
  {
    id: "r5",
    name: "Блинчики с малиной и кремом",
    category: "rc4",
    img: "images/recipes/recipe-5.jpg",
    time: 40,
    difficulty: 2,
  },
  {
    id: "r6",
    name: "Ролл филадельфия",
    category: "rc5",
    img: "images/recipes/recipe-6.jpg",
    time: 30,
    difficulty: 1,
  },
  {
    id: "r7",
    name: "Вишнёвый пирог",
    category: "rc6",
    img: "images/recipes/recipe-7.jpg",
    time: 90,
    difficulty: 3,
  },
  {
    id: "r8",
    name: "Абрикосовое варенье",
    category: "rc7",
    img: "images/recipes/recipe-8.jpg",
    time: 45,
    difficulty: 1,
  },
  {
    id: "r9",
    name: "Мохито",
    category: "rc8",
    img: "images/recipes/recipe-9.jpg",
    time: 10,
    difficulty: 1,
  },
  {
    id: "r10",
    name: "Томатный соус с базиликом",
    category: "rc9",
    img: "images/recipes/recipe-10.jpg",
    time: 20,
    difficulty: 2,
  },
];
